### ISSUE TITLE
ReferenceError: mustache is not defined

### ISSUE THREAD

**Issue by HannesP** [spawnrider/node-red-contrib-http-request#10]
Hi,

I'm trying to use a templated URL but get a runtime error:

    ReferenceError: mustache is not defined at HTTPRequest.<anonymous> (/home/node-red/.node-red/node_modules/node-red-contrib-http-request/www-request.js:37:9)

Looking at the following file, it's evident that `mustache` is being used without having been defined. I suppose there's a require missing?

https://github.com/spawnrider/node-red-contrib-http-request/blob/master/www-request.js

**Comment by spawnrider** [comment]
Just added the **Mustache** dependence to the package.json.
I will release shortly a new **npm** package for it.

**Comment by spawnrider** [comment]
Just released a new **npm** version v0.1.11
