### ISSUE TITLE
Set header Accept: application/json

### ISSUE THREAD

**Issue by hannes-petri-maxiv-lu-se** [spawnrider/node-red-contrib-http-request#12]
For HTTP requests where _Return_ is set to "a parsed JSON object", it would be very useful if the `Accept` header was automatically set to `application/json`.

**Comment by spawnrider** [comment]
Hi, 
Thanks for all your contributions.
Yes, for sure :) 
Could you raise a PR for it ?

**Comment by hannes-petri-maxiv-lu-se** [comment]
Glad to help! PR raised.

**Comment by spawnrider** [comment]
Merged.
Thanks a lot !

**Comment by hannes-petri-maxiv-lu-se** [comment]
Turns out I didn't do it the proper way (even though it should work most of the time). Raised a new, improved PR.
