### ISSUE TITLE
auth with just password

### ISSUE THREAD

**Issue by goeran03** [spawnrider/node-red-contrib-http-request#19]
currently it is obviously not possible to authenticate a website with password only. May be this is not common, but sometimes it can be necessary.
can someone check this?

The following code change would realize the desired result:

 .........

      if (node.ret === "obj") {
        opts.headers.accept = "application/json, text/plain;q=0.9, */*;q=0.8";
      }

      if (this.credentials && this.credentials.user) {
        opts.auth = {
          user: this.credentials.user,
          pass: this.credentials.password,
          sendImmediately: false
        };
      }

      **if (this.credentials && (this.credentials.user==null)) {
        opts.auth = {
          user: "",
          pass: this.credentials.password,
          sendImmediately: false
        };
      }**

      if (tlsNode) {
        tlsNode.addTLSOptions(opts);
      }
..........

G.

**Comment by spawnrider** [comment]
Just released in 0.1.14 version
