### ISSUE TITLE
https via corporate proxy failed

### ISSUE THREAD

**Issue by brusand** [spawnrider/node-red-contrib-http-request#2]
Hi,

i try to send a https request via a corporate proxy and it failed : no SSL Client Hello sent (it works well at home vithout corporate proxy. what i missed ?
he is a wireshark trace :

16	4.587104	10.193.21.110	10.193.115.180	HTTP	93	HTTP/1.1 200 Connection established 
18	4.618792	10.193.21.110	10.193.115.180	TLSv1.2	1314	Server Hello, Certificate
22	4.648370	10.193.21.110	10.193.115.180	TLSv1.2	312	Ignored Unknown Record
24	4.680670	10.193.21.110	10.193.115.180	TLSv1.2	496	Application Data, Encrypted Alert

trace ok with postman
32	5.679083	10.193.115.180	10.193.21.110	HTTP	288	CONNECT integ.m2m.orange.com:443 HTTP/1.1 
35	5.724798	10.193.115.180	10.193.21.110	TLSv1.2	571	Client Hello
37	5.752983	10.193.21.110	10.193.115.180	TLSv1.2	191	Server Hello, Change Cipher Spec, Encrypted Handshake Message
44	5.769509	10.193.115.180	10.193.21.110	HTTP	288	CONNECT integ.m2m.orange.com:443 HTTP/1.1 
47	5.799976	10.193.21.110	10.193.115.180	HTTP	93	HTTP/1.1 200 Connection established 

any idea ?

**Comment by spawnrider** [comment]
Hi,

If I well understood, it works well with Postman ? 
Have you tried to reach google.fr ? Also, using CURL from command line, by setting proxy in Shell.
Could you give me your tests results ? 

Thanks

**Comment by brusand** [comment]
ok, i tried with curl it failed too, but with --insecure (because we aave a self certicate on the server) it is ok. So how can specify an equivalent to curl  option insecure ? 

Regards
Bruno

**Comment by spawnrider** [comment]
Could you try to set this env variable before starting node-red :
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"

**Comment by brusand** [comment]
yep i did already this and even unchecked verify certificats (in the node form) and set env strictSSL = false (i did all of this settings in the prociess.env and in the options data structure and all failed.

my understood was uncheck certificats was similar to --insecure of curl no ?

i want to get works because i have a demo to do soon and based on https in my corporate so via corporate proxy.
Thk, in advance
Bruno

**Comment by spawnrider** [comment]
Did you try to export (or set on Windows) the shell variable with 
```export NODE_TLS_REJECT_UNAUTHORIZED=0```

Or try to import the self-signed certificate into your keystore in order to trust it locally.

**Comment by brusand** [comment]
tried both and still have the error 
<big>Network Error (ssl_server_cert_untrusted_issuer)</big>↵<BR>↵<BR>↵</FONT>↵</TD></TR>↵<TR><TD>↵<FONT face="Helvetica">↵Your request contacted a host which presented a certificate signed by an untrusted issuer.↵</FONT>↵</TD></TR>↵<TR><TD>↵<FONT face="Helvetica">↵This is typically caused by a Web Site presenting an incorrect or invalid certificate, but could be because of a configuration error.↵</FONT>↵</TD></TR>↵<TR><TD>↵<FO

**Comment by brusand** [comment]
i tried to reproduce this isssue with a smaller context and if you had a httpProxyAgent to the opts, it works 

var agent = new HttpsProxyAgent(proxy);
opts.agent = agent;

is it possible to add this in your code ?

thanks in advance
regards
Bruno

**Comment by spawnrider** [comment]
You can send me an "Pull Request" with this fix.
I will add it to the NPM release.
