### ISSUE TITLE
No support for multipart/form-data

### ISSUE THREAD

**Issue by whren** [spawnrider/node-red-contrib-http-request#5]
Hi,

I've found that you've implemented "application/x-www-form-urlencoded" but you did not add the "multipart/form-data" content-type condition so we can't use the [request post formData functionality](https://github.com/request/request#multipartform-data-multipart-form-uploads).

Can you fix this ?
Regards

**Comment by spawnrider** [comment]
Hi,

I'm not currently available to do this fix.
Could you push me a pull request in order to merge this into the NPM released version? 

Best regards,
Yohann
