### ISSUE TITLE
Response URL?

### ISSUE THREAD

**Issue by overclockedtoday** [spawnrider/node-red-contrib-http-request#7]
Greetings,
Is it possible to receive the full response URL in the output, like the default http node in node-red? 

Thanks so much!

**Comment by spawnrider** [comment]
Hi overclockedtoday, 
The best thing you can do is to fork or better, raise an Pull request. 
I will review it and push an new version on NPM.

**Comment by spawnrider** [comment]
Closed in absence of PR
