### ISSUE TITLE
Setting Timeout

### ISSUE THREAD

**Issue by me6ran** [spawnrider/node-red-contrib-http-request#8]
I need to set a timeout for 3-4 seconds on node on my node-red. 
may I ask you how can I set timeout ?

**Comment by nitin20212** [comment]
suggest to leverage node-red-contrib-http-request-ucg or node-red-contrib-http-request-ucg2@0.2.0 - the timeout property is already exposed.

**Comment by spawnrider** [comment]
Closed in absence of PR
